{{- if and .Values.route.enabled .Values.route.ri.host }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "tests-untp-ri.ri.fullname" . }}
  labels:
    {{- include "tests-untp-ri.labels" . | nindent 4 }}
    app.kubernetes.io/component: ri
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  host: {{ .Values.route.ri.host | quote }}
  to:
    kind: Service
    name: {{ include "tests-untp-ri.ri.fullname" . }}
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
