apiVersion: v1
kind: Service
metadata:
  name: {{ include "tests-untp-ri.storage.fullname" . }}
  labels:
    {{- include "tests-untp-ri.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3334
      targetPort: http
  selector:
    {{- include "tests-untp-ri.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: storage
