apiVersion: v1
kind: Service
metadata:
  name: {{ include "tests-untp-ri.minio.fullname" . }}
  labels:
    {{- include "tests-untp-ri.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  type: ClusterIP
  ports:
    - name: api
      port: 9000
      targetPort: api
  selector:
    {{- include "tests-untp-ri.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: minio
