apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "tests-untp-ri.minio.fullname" . }}
  labels:
    {{- include "tests-untp-ri.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  serviceName: {{ include "tests-untp-ri.minio.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "tests-untp-ri.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: minio
  template:
    metadata:
      labels:
        {{- include "tests-untp-ri.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: minio
    spec:
      containers:
        - name: minio
          image: "{{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag }}"
          imagePullPolicy: {{ .Values.minio.image.pullPolicy }}
          args: ["server", "/data", "--console-address", ":9090"]
          ports:
            - name: api
              containerPort: 9000
            - name: console
              containerPort: 9090
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "tests-untp-ri.secretName" . }}
                  key: minio-access-key
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "tests-untp-ri.secretName" . }}
                  key: minio-secret-key
          volumeMounts:
            - name: data
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: api
            initialDelaySeconds: 10
            periodSeconds: 10
          {{- with .Values.minio.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if not .Values.minio.persistence.enabled }}
      volumes:
        - name: data
          emptyDir: {}
      {{- end }}
  {{- if .Values.minio.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.minio.persistence.storageClass }}
        storageClassName: {{ .Values.minio.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.minio.persistence.size }}
  {{- end }}
